name: 'PR Question Template Action'
description: 'Check answers on pull request, and writes the answers to an .sql file'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  template_path:
    description: 'The path to the pr-template file'
    required: true
  sha:
    description: 'The SHA of the PR'
    required: true
  sql_table_name:
    description: 'The name of the sql table'
    required: true
  sql_file_name_create:
    description: 'The name of the create db sql file'
    required: true
  sql_file_name_update:
    description: 'The name of the update db sql file'
    required: true
  sql_file_name_insert:
    description: 'The name of the insert sql file'
    required: true
  number_of_fields_db:
    description: 'The number of questions that the database can hold'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
