name: 'PR Question Action'
description: 'Check answers on pull request, and writes the answers to an .sql file'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  template_path:
    description: 'The path to the pr-template file'
    required: true
  sha:
    description: 'The SHA of the PR'
    required: true
  sql_file_name:
    description: 'The name of the sql file'
    required: true
  number_of_questions:
    description: 'The number of questions that the database can hold'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
