name: 'PR Question Action'
description: 'Check answers on pull request'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  template_path:
    description: 'The path to the pr-template file'
    required: true
outputs:
  answer_1:
    description: 'The answers to question 1'
  answer_2:
    description: 'The answers to question 2'
  answer_3:
    description: 'The answers to question 3'
  answer_4:
    description: 'The answers to question 4'
  answer_5:
    description: 'The answers to question 5'
  answer_6:
    description: 'The answers to question 6'
  answer_7:
    description: 'The answers to question 7'
runs:
  using: 'node16'
  main: 'dist/index.js'
