name: Add questions to PRs

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-questions:
    runs-on: ubuntu-latest
    steps:
      - name: Check questions
        id: check_questions
        uses: ./
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log out the results
        run: echo "Answers ${{steps.check_questions.outputs.answers}}"
