name: Add questions to PRs

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-questions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Check questions
        id: check_questions
        uses: ./
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log out the results
        run: echo "Answers ${{steps.check_questions.outputs.answers}}"

  database-test:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root
      DB_IP: '127.0.0.1'
      DB_PORT: '3306'
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -u ${{ DB_USER}} -p${{ DB_PASSWORD }} \
              -h ${{ DB_ENDPOINT }} -P${{ DB_PORT }} \
              -D ${{ DB_NAME}}
